version: "3.5"

services:
  client:
    image: ${HOST_ARCH}/node:19.0
    container_name: client
    hostname: client.demo
    volumes:
      - ./init.sh:/root/init.sh
      - ./demo:/root/demo
      - ./containerData/client:/root/cmk
    working_dir: /root/demo
    networks:
      qedemo:
        ipv4_address: 192.168.10.10
    environment:
      - TZ=${TIMEZONE}
      - CMK=/root/cmk/master-key.txt
    privileged: true
    entrypoint: bash -c "/root/init.sh && sleep infinity"

  atlas:
    depends_on:
      - client
    build:
      context: containerImages/community
      args:
        HOST_ARCH: ${HOST_ARCH}
    image: ${HOST_ARCH}/ubuntu.mongodb602:community
    container_name: community
    hostname: community.demo
    volumes:
      - ./containerData/community:/root/dbPath
    working_dir: /root
    networks:
      qedemo:
        ipv4_address: 192.168.10.20
    environment:
      - TZ=${TIMEZONE}
      - DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration
      - DB_PATH=/root/dbPath
    privileged: true
    entrypoint: bash -c "\
      echo -e "never" > /sys/kernel/mm/transparent_hugepage/enabled && \
      echo -e "never" > /sys/kernel/mm/transparent_hugepage/defrag && \
      ulimit -n 64000 && \
      mongod -f mongodb.conf && sleep infinity"

  local:
    depends_on:
      - atlas
    build:
      context: containerImages/enterprise
      args:
        HOST_ARCH: ${HOST_ARCH}
    image: ${HOST_ARCH}/ubuntu.mongodb602:enterprise
    container_name: enterprise
    hostname: enterprise.demo
    volumes:
      - ./containerData/enterprise:/root/dbPath
    working_dir: /root
    networks:
      qedemo:
        ipv4_address: 192.168.10.30
    environment:
      - TZ=${TIMEZONE}
      - DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration
      - DB_PATH=/root/dbPath
    privileged: true
    entrypoint: bash -c "\
      echo -e "never" > /sys/kernel/mm/transparent_hugepage/enabled && \
      echo -e "never" > /sys/kernel/mm/transparent_hugepage/defrag && \
      ulimit -n 64000 && \
      mongod -f mongodb.conf && sleep infinity"

networks:
  qedemo:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
