version: "3.5"

services:
  client:
    image: ${HOST_ARCH}/node:19.0
    container_name: client
    hostname: client.demo
    volumes:
      - ./init.sh:/home/node/init.sh
      - ./demo:/home/node/demo
      - client:/home/node/cmk
    working_dir: /home/node/demo
    networks:
      qedemo:
        ipv4_address: 192.168.10.10
    environment:
      - TZ=${TIMEZONE}
      - HOME=/home/node
      - CMK=/home/node/cmk/master-key.txt
      - USE_ATLAS=${USE_ATLAS}
      - ATLAS_CONN_URI=${ATLAS_CONN_URI}
    privileged: true
    entrypoint: bash -c "/home/node/init.sh && sleep infinity"

  atlas:
    depends_on:
      - client
    build:
      context: containerImages/community
      args:
        HOST_ARCH: ${HOST_ARCH}
        DB_PATH: /home/root/dbPath
    image: ${HOST_ARCH}/ubuntu.mongodb602:community
    container_name: community
    hostname: community.demo
    volumes:
      - community:/home/root/dbPath
    working_dir: /home/root
    networks:
      qedemo:
        ipv4_address: 192.168.10.20
    environment:
      - TZ=${TIMEZONE}
      - DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration
    privileged: true

  local:
    depends_on:
      - atlas
    build:
      context: containerImages/enterprise
      args:
        HOST_ARCH: ${HOST_ARCH}
        DB_PATH: /home/root/dbPath
    image: ${HOST_ARCH}/ubuntu.mongodb602:enterprise
    container_name: enterprise
    hostname: enterprise.demo
    volumes:
      - enterprise:/home/root/dbPath
    working_dir: /home/root
    networks:
      qedemo:
        ipv4_address: 192.168.10.30
    environment:
      - TZ=${TIMEZONE}
      - DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration
    privileged: true

networks:
  qedemo:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

volumes:
  client:
  community:
  enterprise:
